### PR TITLE
Update latest translations from Zanata

### PR DESCRIPTION
**Pull request by mariobl**

### CODE REVIEW

**Comment by mariobl** [comment]
Just added a BUGS section to the man pages. Proofreading by a native English speaker is needed. Creating the HTML versions works fine, but the man page creation doesn't:

```
[mariobl@t400 user-docs]$ sphinx-build -b man -c . man _build/man
Running Sphinx v1.8.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
pickling environment... done
writing... WARNING: "man_pages" config value references unknown document man/glabels-qt
WARNING: "man_pages" config value references unknown document man/glabels-batch-qt

build succeeded, 2 warnings.

The manual pages are in _build/man.
```
The man pages are actually not updated due to the warning.

Moreover, I've changed conf.py. The NAME field should show a brief description of what the program does, but "gLabels Documentation" is not very helpful.

**Comment by mariobl** [comment]
Ping...?

**Comment by jimevins** [comment]
> Ping...?

I'm still here.  I have not had much time to devote to glabels lately -- the time I have had has been devoted to the UserVariables branch.

I haven't applied this one yet because it is going to require more manual intervention than I currently have the mental bandwidth for.  This is because it was done on your master branch and includes artifacts from your previous pull requests.  Ideally each pull request should be on its own branch so that it is a self-contained idea.

**Comment by mariobl** [comment]
Sorry for the inconvenience. I was not aware of the new branch, and in general I'm not very familiar with the workflow regarding merge requests. I will split the changes in branches now.

**Pull request closed without merging**
